#!/bin/bash

request=(\
  "GET / HTTP/1.1\r\nHost: 192.168.93.235\r\n\r\n"\
  "GET / HTTP/2.0\r\nHost: 192.168.93.235\r\n\r\n"\
  " / HTTP/1.1\r\nHost: 192.168.93.235\r\n\r\n"\
)

signature=(\
    "HTTP/1.1 2"\
    "HTTP/1.1 5"\
    "HTTP/1.1 400"\
)

valid_pattern=(\
    "0"\
    "0 1"\
    "2"\
)
